services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./backend/scripts:/app/scripts
    environment:
      - DOMAIN=fastapi-dev.local
      - FRONTEND_HOST=http://fastapi-dev.local:5173
      - ENVIRONMENT=local
      - PROJECT_NAME=FastAPI Template
      - BACKEND_CORS_ORIGINS=["http://fastapi-dev.local:5173","http://fastapi-dev.local:8000","http://localhost:5173","http://localhost:8000"]
      - SECRET_KEY=OMOrH-1eg4PSCuzw2Aj9g2JmvxiVlcv6zi0nxpeCFl8
      - FIRST_SUPERUSER=admin@example.com
      - FIRST_SUPERUSER_PASSWORD=admin123
      - SMTP_HOST=mailcatcher
      - SMTP_PORT=1025
      - SMTP_TLS=false
      - EMAILS_FROM_EMAIL=noreply@example.com
      - POSTGRES_SERVER=host.docker.internal
      - POSTGRES_PORT=5432
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: ["fastapi", "run", "--host", "0.0.0.0", "--port", "8000", "--reload", "app/main.py"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_URL=http://fastapi-dev.local:8000
        - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - ./frontend/index.html:/app/index.html
      - ./frontend/vite.config.ts:/app/vite.config.ts
      - ./frontend/tsconfig.json:/app/tsconfig.json
      - ./frontend/tsconfig.build.json:/app/tsconfig.build.json
      - ./frontend/tsconfig.node.json:/app/tsconfig.node.json

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DESIGN=pepa-linha-dark

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
