// This file is auto-generated by @hey-api/openapi-ts

export type AccountCreate = {
    name: string;
    type?: AccountType;
    currency?: string;
    is_active?: boolean;
};

export type AccountPublic = {
    name: string;
    type?: AccountType;
    currency?: string;
    is_active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type AccountsPublic = {
    data: Array<AccountPublic>;
    count: number;
};

export type AccountType = 'cash' | 'bank' | 'ewallet' | 'investment' | 'credit_card' | 'other';

export type AccountUpdate = {
    name?: (string | null);
    type?: (AccountType | null);
    currency?: (string | null);
    is_active?: (boolean | null);
};

export type AllocationRuleCreate = {
    grp: CategoryGroup;
    percent: number;
    sprint_id?: (string | null);
};

export type AllocationRulePublic = {
    grp: CategoryGroup;
    percent: number;
    id: string;
    user_id: string;
    sprint_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type AllocationRulesPublic = {
    data: Array<AllocationRulePublic>;
    count: number;
};

export type AllocationRuleUpdate = {
    grp?: (CategoryGroup | null);
    percent?: (number | null);
    sprint_id?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoriesPublic = {
    data: Array<CategoryPublic>;
    count: number;
};

export type CategoryCreate = {
    name: string;
    grp: CategoryGroup;
    is_envelope?: boolean;
};

export type CategoryGroup = 'needs' | 'wants' | 'savings_debt';

export type CategoryPublic = {
    name: string;
    grp: CategoryGroup;
    is_envelope?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type CategoryUpdate = {
    name?: (string | null);
    grp?: (CategoryGroup | null);
    is_envelope?: (boolean | null);
};

export type EmailTransactionPublic = {
    email_id: string;
    subject: string;
    sender: string;
    received_at: string;
    amount?: (number | null);
    merchant?: (string | null);
    account_number?: (string | null);
    transaction_type?: (string | null);
    status?: EmailTransactionStatus;
    raw_content?: (string | null);
    id: string;
    gmail_connection_id: string;
    linked_transaction_id: (string | null);
    category_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type EmailTransactionsPublic = {
    data: Array<EmailTransactionPublic>;
    count: number;
};

export type EmailTransactionStatus = 'pending' | 'processed' | 'ignored';

export type EmailTransactionUpdate = {
    amount?: (number | null);
    merchant?: (string | null);
    account_number?: (string | null);
    transaction_type?: (string | null);
    status?: (EmailTransactionStatus | null);
    linked_transaction_id?: (string | null);
    category_id?: (string | null);
};

export type EmailTxnCategoryAmount = {
    category_id?: (string | null);
    category_name?: (string | null);
    total_amount?: number;
};

export type EmailTxnDashboard = {
    by_category?: Array<EmailTxnCategoryAmount>;
    monthly?: Array<EmailTxnMonthlyAmount>;
};

export type EmailTxnMonthlyAmount = {
    year: number;
    month: number;
    total_amount?: number;
};

export type GmailConnectionPublic = {
    gmail_email: string;
    is_active?: boolean;
    id: string;
    user_id: string;
    expires_at: (string | null);
    last_sync_at: (string | null);
    created_at: string;
    updated_at: string;
};

export type GmailConnectionsPublic = {
    data: Array<GmailConnectionPublic>;
    count: number;
};

export type GmailConnectionUpdate = {
    is_active?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IncomeCreate = {
    received_at: string;
    source: string;
    gross_amount: number;
    net_amount: number;
    currency?: string;
    sprint_id?: (string | null);
};

export type IncomePublic = {
    received_at: string;
    source: string;
    gross_amount: number;
    net_amount: number;
    currency?: string;
    id: string;
    user_id: string;
    sprint_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type IncomesPublic = {
    data: Array<IncomePublic>;
    count: number;
};

export type IncomeUpdate = {
    received_at?: (string | null);
    source?: (string | null);
    gross_amount?: (number | null);
    net_amount?: (number | null);
    currency?: (string | null);
    sprint_id?: (string | null);
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
};

export type Message = {
    message: string;
};

export type MonthlyFinancialReport = {
    year: number;
    month: number;
    total_income?: number;
    total_expenses?: number;
    net_amount?: number;
    income_count?: number;
    expense_count?: number;
    incomes?: Array<IncomePublic>;
    transactions?: Array<TransactionPublic>;
    allocation_rules?: Array<AllocationRulePublic>;
};

export type MonthlyFinancialReports = {
    data: Array<MonthlyFinancialReport>;
    count: number;
};

export type MonthlyFinancialSummary = {
    year: number;
    month: number;
    total_income?: number;
    total_expenses?: number;
    net_amount?: number;
    income_count?: number;
    expense_count?: number;
    category_breakdown?: {
        [key: string]: (number);
    };
    account_breakdown?: {
        [key: string]: (number);
    };
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type SprintCreate = {
    start_date: string;
    end_date: string;
    payday_anchor: string;
    is_closed?: boolean;
};

export type SprintDetailPublic = {
    start_date: string;
    end_date: string;
    payday_anchor: string;
    is_closed?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
    incomes?: Array<IncomePublic>;
    transactions?: Array<TransactionPublic>;
    allocation_rules?: Array<AllocationRulePublic>;
    accounts?: Array<AccountPublic>;
    categories?: Array<CategoryPublic>;
    financial_summary?: {
        [key: string]: unknown;
    };
};

export type SprintPublic = {
    start_date: string;
    end_date: string;
    payday_anchor: string;
    is_closed?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type SprintsPublic = {
    data: Array<SprintPublic>;
    count: number;
};

export type SprintUpdate = {
    start_date?: (string | null);
    end_date?: (string | null);
    payday_anchor?: (string | null);
    is_closed?: (boolean | null);
};

export type TodoCreate = {
    title: string;
    description?: (string | null);
    is_completed?: boolean;
};

export type TodoPublic = {
    title: string;
    description?: (string | null);
    is_completed?: boolean;
    id: string;
    owner_id: string;
    created_at: string;
    updated_at: string;
};

export type TodosPublic = {
    data: Array<TodoPublic>;
    count: number;
};

export type TodoUpdate = {
    title?: (string | null);
    description?: (string | null);
    is_completed?: (boolean | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TransactionCreate = {
    txn_date: string;
    type: TxnType;
    amount: number;
    currency?: string;
    merchant?: (string | null);
    note?: (string | null);
    account_id: string;
    category_id?: (string | null);
    sprint_id?: (string | null);
};

export type TransactionPublic = {
    txn_date: string;
    type: TxnType;
    amount: number;
    currency?: string;
    merchant?: (string | null);
    note?: (string | null);
    id: string;
    user_id: string;
    sprint_id: (string | null);
    account_id: string;
    category_id: (string | null);
    created_at: string;
    updated_at: string;
};

export type TransactionsPublic = {
    data: Array<TransactionPublic>;
    count: number;
};

export type TransactionUpdate = {
    txn_date?: (string | null);
    type?: (TxnType | null);
    amount?: (number | null);
    currency?: (string | null);
    merchant?: (string | null);
    note?: (string | null);
    account_id?: (string | null);
    category_id?: (string | null);
    sprint_id?: (string | null);
};

export type TxnType = 'in' | 'out';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    is_superuser?: (boolean | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AccountsReadAccountsData = {
    limit?: number;
    skip?: number;
};

export type AccountsReadAccountsResponse = (AccountsPublic);

export type AccountsCreateAccountData = {
    requestBody: AccountCreate;
};

export type AccountsCreateAccountResponse = (AccountPublic);

export type AccountsUpdateAccountData = {
    accountId: string;
    requestBody: AccountUpdate;
};

export type AccountsUpdateAccountResponse = (AccountPublic);

export type AccountsReadAccountData = {
    accountId: string;
};

export type AccountsReadAccountResponse = (AccountPublic);

export type AccountsDeleteAccountData = {
    accountId: string;
};

export type AccountsDeleteAccountResponse = (Message);

export type AllocationRulesReadAllocationRulesData = {
    limit?: number;
    skip?: number;
};

export type AllocationRulesReadAllocationRulesResponse = (AllocationRulesPublic);

export type AllocationRulesCreateAllocationRuleData = {
    requestBody: AllocationRuleCreate;
};

export type AllocationRulesCreateAllocationRuleResponse = (AllocationRulePublic);

export type AllocationRulesUpdateAllocationRuleData = {
    allocationRuleId: string;
    requestBody: AllocationRuleUpdate;
};

export type AllocationRulesUpdateAllocationRuleResponse = (AllocationRulePublic);

export type AllocationRulesReadAllocationRuleData = {
    allocationRuleId: string;
};

export type AllocationRulesReadAllocationRuleResponse = (AllocationRulePublic);

export type AllocationRulesDeleteAllocationRuleData = {
    allocationRuleId: string;
};

export type AllocationRulesDeleteAllocationRuleResponse = (Message);

export type CategoriesReadCategoriesData = {
    limit?: number;
    skip?: number;
};

export type CategoriesReadCategoriesResponse = (CategoriesPublic);

export type CategoriesCreateCategoryData = {
    requestBody: CategoryCreate;
};

export type CategoriesCreateCategoryResponse = (CategoryPublic);

export type CategoriesUpdateCategoryData = {
    categoryId: string;
    requestBody: CategoryUpdate;
};

export type CategoriesUpdateCategoryResponse = (CategoryPublic);

export type CategoriesReadCategoryData = {
    categoryId: string;
};

export type CategoriesReadCategoryResponse = (CategoryPublic);

export type CategoriesDeleteCategoryData = {
    categoryId: string;
};

export type CategoriesDeleteCategoryResponse = (Message);

export type GmailGetGmailConnectionsData = {
    limit?: number;
    skip?: number;
};

export type GmailGetGmailConnectionsResponse = (GmailConnectionsPublic);

export type GmailInitiateGmailConnectionResponse = ({
    [key: string]: unknown;
});

export type GmailHandleGmailCallbackData = {
    /**
     * Authorization code from Google
     */
    code: string;
    /**
     * State parameter for security
     */
    state: string;
};

export type GmailHandleGmailCallbackResponse = (GmailConnectionPublic);

export type GmailUpdateGmailConnectionData = {
    connectionId: string;
    requestBody: GmailConnectionUpdate;
};

export type GmailUpdateGmailConnectionResponse = (GmailConnectionPublic);

export type GmailDeleteGmailConnectionData = {
    connectionId: string;
};

export type GmailDeleteGmailConnectionResponse = (Message);

export type GmailGetEmailTransactionsData = {
    /**
     * Gmail connection ID
     */
    connectionId: string;
    limit?: number;
    skip?: number;
    /**
     * Filter by status (pending, processed, ignored)
     */
    status?: string;
};

export type GmailGetEmailTransactionsResponse = (EmailTransactionsPublic);

export type GmailSyncEmailsData = {
    /**
     * Gmail connection ID
     */
    connectionId: string;
    /**
     * Maximum number of emails to sync
     */
    maxResults?: number;
};

export type GmailSyncEmailsResponse = (Message);

export type GmailSyncEmailsByMonthData = {
    /**
     * Gmail connection ID
     */
    connectionId: string;
    /**
     * Maximum number of emails to sync
     */
    maxResults?: number;
    /**
     * Month to sync (1-12)
     */
    month: number;
    /**
     * Year to sync (e.g., 2024)
     */
    year: number;
};

export type GmailSyncEmailsByMonthResponse = (Message);

export type GmailUpdateEmailTransactionData = {
    requestBody: EmailTransactionUpdate;
    transactionId: string;
};

export type GmailUpdateEmailTransactionResponse = (EmailTransactionPublic);

export type GmailDeleteEmailTransactionData = {
    transactionId: string;
};

export type GmailDeleteEmailTransactionResponse = (Message);

export type GmailGetEmailTransactionsDashboardData = {
    /**
     * Gmail connection ID
     */
    connectionId: string;
    /**
     * Month filter (1-12)
     */
    month?: (number | null);
    /**
     * Year filter for monthly chart
     */
    year?: (number | null);
};

export type GmailGetEmailTransactionsDashboardResponse = (EmailTxnDashboard);

export type IncomesReadIncomesData = {
    limit?: number;
    skip?: number;
};

export type IncomesReadIncomesResponse = (IncomesPublic);

export type IncomesCreateIncomeData = {
    requestBody: IncomeCreate;
};

export type IncomesCreateIncomeResponse = (IncomePublic);

export type IncomesUpdateIncomeData = {
    incomeId: string;
    requestBody: IncomeUpdate;
};

export type IncomesUpdateIncomeResponse = (IncomePublic);

export type IncomesReadIncomeData = {
    incomeId: string;
};

export type IncomesReadIncomeResponse = (IncomePublic);

export type IncomesDeleteIncomeData = {
    incomeId: string;
};

export type IncomesDeleteIncomeResponse = (Message);

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type MonthlyReportsGetMonthlyFinancialSummaryData = {
    month: number;
    year: number;
};

export type MonthlyReportsGetMonthlyFinancialSummaryResponse = (MonthlyFinancialSummary);

export type MonthlyReportsGetMonthlyFinancialReportData = {
    month: number;
    year: number;
};

export type MonthlyReportsGetMonthlyFinancialReportResponse = (MonthlyFinancialReport);

export type MonthlyReportsGetMonthlyFinancialReportsRangeData = {
    /**
     * End month (1-12)
     */
    endMonth: number;
    /**
     * End year
     */
    endYear: number;
    /**
     * Start month (1-12)
     */
    startMonth: number;
    /**
     * Start year
     */
    startYear: number;
};

export type MonthlyReportsGetMonthlyFinancialReportsRangeResponse = (MonthlyFinancialReports);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type SprintsReadSprintsData = {
    limit?: number;
    skip?: number;
};

export type SprintsReadSprintsResponse = (SprintsPublic);

export type SprintsCreateSprintData = {
    requestBody: SprintCreate;
};

export type SprintsCreateSprintResponse = (SprintPublic);

export type SprintsUpdateSprintData = {
    requestBody: SprintUpdate;
    sprintId: string;
};

export type SprintsUpdateSprintResponse = (SprintPublic);

export type SprintsReadSprintData = {
    sprintId: string;
};

export type SprintsReadSprintResponse = (SprintPublic);

export type SprintsDeleteSprintData = {
    sprintId: string;
};

export type SprintsDeleteSprintResponse = (Message);

export type SprintsReadSprintDetailData = {
    sprintId: string;
};

export type SprintsReadSprintDetailResponse = (SprintDetailPublic);

export type TodosReadTodosData = {
    limit?: number;
    skip?: number;
};

export type TodosReadTodosResponse = (TodosPublic);

export type TodosCreateTodoEndpointData = {
    requestBody: TodoCreate;
};

export type TodosCreateTodoEndpointResponse = (TodoPublic);

export type TodosReadTodoData = {
    id: string;
};

export type TodosReadTodoResponse = (TodoPublic);

export type TodosUpdateTodoEndpointData = {
    id: string;
    requestBody: TodoUpdate;
};

export type TodosUpdateTodoEndpointResponse = (TodoPublic);

export type TodosDeleteTodoEndpointData = {
    id: string;
};

export type TodosDeleteTodoEndpointResponse = (Message);

export type TransactionsReadTransactionsData = {
    limit?: number;
    skip?: number;
};

export type TransactionsReadTransactionsResponse = (TransactionsPublic);

export type TransactionsCreateTransactionData = {
    requestBody: TransactionCreate;
};

export type TransactionsCreateTransactionResponse = (TransactionPublic);

export type TransactionsUpdateTransactionData = {
    requestBody: TransactionUpdate;
    transactionId: string;
};

export type TransactionsUpdateTransactionResponse = (TransactionPublic);

export type TransactionsReadTransactionData = {
    transactionId: string;
};

export type TransactionsReadTransactionResponse = (TransactionPublic);

export type TransactionsDeleteTransactionData = {
    transactionId: string;
};

export type TransactionsDeleteTransactionResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);