# Import all CRUD functions from individual modules
from .user import (
    authenticate,
    create_user,
    get_user_by_email,
    update_user,
)
from .todo import (
    create_checklist_item,
    create_item,
    create_todo,
    delete_checklist_item,
    delete_todo,
    get_checklist_item,
    get_checklist_items_by_todo,
    get_todo_children,
    get_todo_parent,
    get_todo,
    get_todos,
    get_todos_by_milestone,
    get_todo_milestone,
    get_todos_by_subject,
    get_todo_subject,
    update_checklist_item,
    update_todo,
    get_todos_for_date,
    get_completed_todos_for_date,
    get_overdue_todos,
    schedule_todo_for_date,
    rollover_overdue_todos,
    get_daily_schedule_summary,
)
from .account import (
    create_account,
    delete_account,
    get_account,
    get_accounts,
    update_account,
)
from .category import (
    create_category,
    delete_category,
    get_category,
    get_categories,
    update_category,
)
from .transaction import (
    create_transaction,
    delete_transaction,
    get_transaction,
    get_transactions,
    update_transaction,
)
from .allocation_rule import (
    create_allocation_rule,
    delete_allocation_rule,
    get_allocation_rule,
    get_allocation_rules,
    update_allocation_rule,
)
from .gmail_connection import (
    create_gmail_connection,
    delete_gmail_connection,
    get_active_gmail_connection,
    get_gmail_connection_by_user_and_email,
    get_gmail_connection,
    get_gmail_connections,
    update_gmail_connection,
)
from .email_transaction import (
    bulk_update_email_transactions,
    count_email_transactions,
    create_email_transaction,
    delete_email_transaction,
    get_email_transaction,
    get_email_transaction_by_email_id,
    get_email_transactions,
    get_pending_email_transactions,
    get_email_txn_dashboard,
    update_email_transaction,
    get_email_transactions_for_all_connections,
)
from .roadmap import (
    create_roadmap,
    delete_roadmap,
    get_roadmap,
    get_roadmap_with_milestones,
    get_roadmaps,
    update_roadmap,
    create_milestone,
    delete_milestone,
    get_milestone,
    get_milestones_by_roadmap,
    update_milestone,
    reorder_milestones,
)
from .resource import (
    create_resource,
    delete_resource,
    get_resource,
    get_resources,
    update_resource,
    create_resource_subject,
    delete_resource_subject,
    get_resource_subject,
    get_resource_subjects,
    update_resource_subject,
    reorder_resource_subjects,
)
from .feedback import (
    create_feedback,
    delete_feedback,
    get_feedback,
    get_feedbacks,
    update_feedback,
)

__all__ = [
    # User functions
    "authenticate",
    "create_user",
    "get_user_by_email",
    "update_user",
    # Todo/Item functions
    "create_item",
    "create_todo",
    "delete_todo",
    "get_todo",
    "get_todos",
    "update_todo",
    "get_todo_children",
    "get_todo_parent",
    "get_todos_by_milestone",
    "get_todo_milestone",
    "get_todos_by_subject",
    "get_todo_subject",
    # Checklist functions
    "create_checklist_item",
    "delete_checklist_item",
    "get_checklist_item",
    "get_checklist_items_by_todo",
    "update_checklist_item",
    # Daily scheduling functions
    "get_todos_for_date",
    "get_completed_todos_for_date",
    "get_overdue_todos",
    "schedule_todo_for_date",
    "rollover_overdue_todos",
    "get_daily_schedule_summary",
    # Sprint functions
    "create_sprint",
    "delete_sprint",
    "get_sprint",
    "get_sprint_detail",
    "get_sprints",
    "update_sprint",
    # Account functions
    "create_account",
    "delete_account",
    "get_account",
    "get_accounts",
    "update_account",
    # Category functions
    "create_category",
    "delete_category",
    "get_category",
    "get_categories",
    "update_category",
    # Transaction functions
    "create_transaction",
    "delete_transaction",
    "get_transaction",
    "get_transactions",
    "update_transaction",
    # Allocation rule functions
    "create_allocation_rule",
    "delete_allocation_rule",
    "get_allocation_rule",
    "get_allocation_rules",
    "update_allocation_rule",
    # Gmail connection functions
    "create_gmail_connection",
    "delete_gmail_connection",
    "get_active_gmail_connection",
    "get_gmail_connection_by_user_and_email",
    "get_gmail_connection",
    "get_gmail_connections",
    "update_gmail_connection",
    # Email transaction functions
    "bulk_update_email_transactions",
    "count_email_transactions",
    "create_email_transaction",
    "delete_email_transaction",
    "get_email_transaction",
    "get_email_transaction_by_email_id",
    "get_email_transactions",
    "get_pending_email_transactions",
    "get_email_txn_dashboard",
    "update_email_transaction",
    "get_email_transactions_for_all_connections",
    # Roadmap functions
    "create_roadmap",
    "delete_roadmap",
    "get_roadmap",
    "get_roadmap_with_milestones",
    "get_roadmaps",
    "update_roadmap",
    # Milestone functions
    "create_milestone",
    "delete_milestone",
    "get_milestone",
    "get_milestones_by_roadmap",
    "update_milestone",
    "reorder_milestones",
    # Resource functions
    "create_resource",
    "delete_resource",
    "get_resource",
    "get_resources",
    "update_resource",
    # Resource subject functions
    "create_resource_subject",
    "delete_resource_subject",
    "get_resource_subject",
    "get_resource_subjects",
    "update_resource_subject",
    "reorder_resource_subjects",
    # Feedback functions
    "create_feedback",
    "delete_feedback",
    "get_feedback",
    "get_feedbacks",
    "update_feedback",
]
