"""Remove order_index from roadmap milestone table

Revision ID: 158918d2bb37
Revises: 7585e4a01af7
Create Date: 2025-09-27 19:37:42.490639

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '158918d2bb37'
down_revision = '7585e4a01af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
