"""refactor_income_to_single_amount_field

Revision ID: 19a1ce83ee03
Revises: 8cd1bea0b867
Create Date: 2025-09-18 23:37:46.146384

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '19a1ce83ee03'
down_revision = '8cd1bea0b867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the new amount column
    op.add_column('income', sa.Column('amount', sa.Float(), nullable=True))
    
    # Migrate existing data: use net_amount if available, otherwise gross_amount
    op.execute("""
        UPDATE income 
        SET amount = COALESCE(net_amount, gross_amount)
        WHERE amount IS NULL
    """)
    
    # Make amount column non-nullable after data migration
    op.alter_column('income', 'amount', nullable=False)
    
    # Drop the old columns
    op.drop_column('income', 'gross_amount')
    op.drop_column('income', 'net_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('net_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('income', sa.Column('gross_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('income', 'amount')
    # ### end Alembic commands ###
