"""Remove roadmap_id from Resource model

Revision ID: 22f768cb411d
Revises: 667c8423e9a2
Create Date: 2025-09-28 21:11:10.266159

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '22f768cb411d'
down_revision = '667c8423e9a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resource_roadmap_id_fkey'), 'resource', type_='foreignkey')
    op.drop_column('resource', 'roadmap_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('roadmap_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('resource_roadmap_id_fkey'), 'resource', 'roadmap', ['roadmap_id'], ['id'])
    # ### end Alembic commands ###
