"""Add type field to Todo

Revision ID: 28078713b8a4
Revises: 470f4e441336
Create Date: 2025-09-23 09:05:27.116186

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '28078713b8a4'
down_revision = '470f4e441336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    todotype_enum = sa.Enum('work', 'learning', 'daily_life', 'task', 'personal', 'health', 'finance', 'other', name='todotype')
    todotype_enum.create(op.get_bind())
    
    op.add_column('todo', sa.Column('type', todotype_enum, nullable=False, server_default='task'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'type')
    
    # Drop the enum type
    todotype_enum = sa.Enum('work', 'learning', 'daily_life', 'task', 'personal', 'health', 'finance', 'other', name='todotype')
    todotype_enum.drop(op.get_bind())
    # ### end Alembic commands ###
