"""Add monthly financial reports models

Revision ID: 2cbf19f9448b
Revises: 34306601a85d
Create Date: 2025-09-15 10:54:55.631041

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2cbf19f9448b'
down_revision = '34306601a85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
