"""make_sprint_id_optional_for_income_and_allocation_rule

Revision ID: 34306601a85d
Revises: 00eb599e3aae
Create Date: 2025-09-15 10:21:52.103189

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '34306601a85d'
down_revision = '00eb599e3aae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Make sprint_id nullable for income table
    op.alter_column('income', 'sprint_id',
               existing_type=sa.UUID(),
               nullable=True)
    
    # Make sprint_id nullable for allocationrule table
    op.alter_column('allocationrule', 'sprint_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert sprint_id to not nullable for income table
    op.alter_column('income', 'sprint_id',
               existing_type=sa.UUID(),
               nullable=False)
    
    # Revert sprint_id to not nullable for allocationrule table
    op.alter_column('allocationrule', 'sprint_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
