"""add_milestone_id_to_todo

Revision ID: 3feff8d38071
Revises: a27aa4155ac4
Create Date: 2025-09-28 14:45:23.410843

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3feff8d38071'
down_revision = 'a27aa4155ac4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('milestone_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'todo', 'roadmapmilestone', ['milestone_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'milestone_id')
    # ### end Alembic commands ###
