"""Add estimate_minutes and priority to Todo

Revision ID: 470f4e441336
Revises: 14210bdacbdf
Create Date: 2025-09-22 23:46:09.039029

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '470f4e441336'
down_revision = '14210bdacbdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    todopriority_enum = sa.Enum('low', 'medium', 'high', 'urgent', name='todopriority')
    todopriority_enum.create(op.get_bind())
    
    op.add_column('todo', sa.Column('estimate_minutes', sa.Integer(), nullable=True))
    op.add_column('todo', sa.Column('priority', todopriority_enum, nullable=False, server_default='medium'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'priority')
    op.drop_column('todo', 'estimate_minutes')
    
    # Drop the enum type
    todopriority_enum = sa.Enum('low', 'medium', 'high', 'urgent', name='todopriority')
    todopriority_enum.drop(op.get_bind())
    # ### end Alembic commands ###
