"""Add due_date to todo, milestone, and resource_subject

Revision ID: 4da9c6abddae
Revises: 9c36157290ab
Create Date: 2025-10-02 12:38:57.856312

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '4da9c6abddae'
down_revision = '9c36157290ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resourcesubject', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('roadmapmilestone', sa.Column('due_date', sa.Date(), nullable=True))
    op.add_column('todo', sa.Column('due_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'due_date')
    op.drop_column('roadmapmilestone', 'due_date')
    op.drop_column('resourcesubject', 'due_date')
    # ### end Alembic commands ###
