"""remove_seen_field_from_email_transaction

Revision ID: 54c51efca7db
Revises: 69c96cbcf99a
Create Date: 2025-09-21 21:52:24.521813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '54c51efca7db'
down_revision = '69c96cbcf99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailtransaction', 'seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailtransaction', sa.Column('seen', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
