"""add_linked_income_id_to_email_transaction

Revision ID: 63d62c50b0a0
Revises: 19a1ce83ee03
Create Date: 2025-09-18 23:50:20.069125

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '63d62c50b0a0'
down_revision = '19a1ce83ee03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailtransaction', sa.Column('linked_income_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'emailtransaction', 'income', ['linked_income_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emailtransaction', type_='foreignkey')
    op.drop_column('emailtransaction', 'linked_income_id')
    # ### end Alembic commands ###
