"""Remove attachment fields from Resource model

Revision ID: 667c8423e9a2
Revises: 10e429955981
Create Date: 2025-09-28 21:02:48.888821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '667c8423e9a2'
down_revision = '10e429955981'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'resource_type')
    op.drop_column('resource', 'file_size')
    op.drop_column('resource', 'file_path')
    op.drop_column('resource', 'mime_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('resource', sa.Column('resource_type', postgresql.ENUM('course', 'book', 'document', 'video', 'article', 'tool', name='resourcetype'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
