"""add_income_to_txn_type_enum

Revision ID: 69c96cbcf99a
Revises: cd56bd3be81c
Create Date: 2025-09-21 17:22:40.290233

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '69c96cbcf99a'
down_revision = 'cd56bd3be81c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
