"""add_subject_id_to_todo_table

Revision ID: 7576e3521d33
Revises: f0e7635290a9
Create Date: 2025-09-30 23:04:51.455406

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7576e3521d33'
down_revision = 'f0e7635290a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('subject_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'todo', 'resourcesubject', ['subject_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'subject_id')
    # ### end Alembic commands ###
