"""Remove progress_percentage from roadmap table

Revision ID: 7585e4a01af7
Revises: b977936c229c
Create Date: 2025-09-27 19:29:13.045165

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7585e4a01af7'
down_revision = 'b977936c229c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap', 'progress_percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap', sa.Column('progress_percentage', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
