"""add_income_to_category_group

Revision ID: 7f15f0079160
Revises: 54c51efca7db
Create Date: 2025-09-21 23:04:07.047274

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f15f0079160'
down_revision = '54c51efca7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
