"""Add seen field to email transaction

Revision ID: 852afae593c8
Revises: 932ae061626d
Create Date: 2025-09-17 09:42:46.429738

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '852afae593c8'
down_revision = '932ae061626d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first
    op.add_column('emailtransaction', sa.Column('seen', sa.Boolean(), nullable=False, server_default='false'))
    # Remove server default after adding the column
    op.alter_column('emailtransaction', 'seen', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emailtransaction', 'seen')
    # ### end Alembic commands ###
