"""Add SET NULL cascade to emailtransaction linked_transaction_id

Revision ID: 8cd1bea0b867
Revises: 852afae593c8
Create Date: 2025-09-18 11:56:19.914092

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8cd1bea0b867'
down_revision = '852afae593c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emailtransaction_linked_transaction_id_fkey'), 'emailtransaction', type_='foreignkey')
    op.create_foreign_key(None, 'emailtransaction', 'transaction', ['linked_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emailtransaction', type_='foreignkey')
    op.create_foreign_key(op.f('emailtransaction_linked_transaction_id_fkey'), 'emailtransaction', 'transaction', ['linked_transaction_id'], ['id'])
    # ### end Alembic commands ###
