"""add category_id to emailtransaction

Revision ID: 932ae061626d
Revises: db02b510991e
Create Date: 2025-09-16 16:06:21.581135

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '932ae061626d'
down_revision = 'db02b510991e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailtransaction', sa.Column('category_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'emailtransaction', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'emailtransaction', type_='foreignkey')
    op.drop_column('emailtransaction', 'category_id')
    # ### end Alembic commands ###
