"""add parent_id to todo with self fk set null

Revision ID: 965249ccd6e5
Revises: 28078713b8a4
Create Date: 2025-09-23 14:19:01.904850

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '965249ccd6e5'
down_revision = '28078713b8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('parent_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'todo', 'todo', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'parent_id')
    # ### end Alembic commands ###
