"""Add questions field to milestone

Revision ID: 9c36157290ab
Revises: dc4609e67e21
Create Date: 2025-10-02 10:31:22.406868

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9c36157290ab'
down_revision = 'dc4609e67e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmapmilestone', sa.Column('questions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmapmilestone', 'questions')
    # ### end Alembic commands ###
