"""Add ai_chat_url field to Resource

Revision ID: 9ca51daab482
Revises: da670b764a51
Create Date: 2025-10-03 22:47:32.146352

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ca51daab482'
down_revision = 'da670b764a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource', sa.Column('ai_chat_url', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource', 'ai_chat_url')
    # ### end Alembic commands ###
