"""Remove order_index from roadmap milestone table - final

Revision ID: a27aa4155ac4
Revises: 158918d2bb37
Create Date: 2025-09-27 19:39:22.587717

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a27aa4155ac4'
down_revision = '158918d2bb37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmapmilestone', 'order_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmapmilestone', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
