"""Remove income tables and references

Revision ID: cd56bd3be81c
Revises: d80a80472506
Create Date: 2025-09-21 16:57:43.449197

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd56bd3be81c'
down_revision = 'd80a80472506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First drop the foreign key constraint and column
    op.drop_constraint(op.f('emailtransaction_linked_income_id_fkey'), 'emailtransaction', type_='foreignkey')
    op.drop_column('emailtransaction', 'linked_income_id')
    # Then drop the income table
    op.drop_table('income')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emailtransaction', sa.Column('linked_income_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('emailtransaction_linked_income_id_fkey'), 'emailtransaction', 'income', ['linked_income_id'], ['id'], ondelete='SET NULL')
    op.create_table('income',
    sa.Column('received_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('income_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('income_pkey'))
    )
    # ### end Alembic commands ###
