"""add learning_objectives to resourcesubject

Revision ID: d6dd39c7830d
Revises: 7576e3521d33
Create Date: 2025-10-01 20:12:16.138852

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'd6dd39c7830d'
down_revision = '7576e3521d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resourcesubject', sa.Column('learning_objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resourcesubject', 'learning_objectives')
    # ### end Alembic commands ###
