"""Rename scheduled_date to planned_date in todo

Revision ID: da670b764a51
Revises: 4da9c6abddae
Create Date: 2025-10-02 15:18:06.581527

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'da670b764a51'
down_revision = '4da9c6abddae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column to preserve data
    op.alter_column('todo', 'scheduled_date', new_column_name='planned_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename column back to preserve data
    op.alter_column('todo', 'planned_date', new_column_name='scheduled_date')
    # ### end Alembic commands ###
