"""add_gmail_integration_models

Revision ID: db02b510991e
Revises: 2cbf19f9448b
Create Date: 2025-09-15 12:07:09.852595

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db02b510991e'
down_revision = '2cbf19f9448b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmailconnection',
    sa.Column('gmail_email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('access_token', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('refresh_token', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emailtransaction',
    sa.Column('email_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('merchant', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('account_number', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processed', 'ignored', name='emailtransactionstatus'), nullable=False),
    sa.Column('raw_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('gmail_connection_id', sa.Uuid(), nullable=False),
    sa.Column('linked_transaction_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gmail_connection_id'], ['gmailconnection.id'], ),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailtransaction_email_id'), 'emailtransaction', ['email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailtransaction_email_id'), table_name='emailtransaction')
    op.drop_table('emailtransaction')
    op.drop_table('gmailconnection')
    # ### end Alembic commands ###
