"""add learning_objectives to milestone

Revision ID: dc4609e67e21
Revises: d6dd39c7830d
Create Date: 2025-10-02 08:42:06.855264

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dc4609e67e21'
down_revision = 'd6dd39c7830d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmapmilestone', sa.Column('learning_objectives', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmapmilestone', 'learning_objectives')
    # ### end Alembic commands ###
