"""add_scheduled_date_to_todos

Revision ID: e49a289a6c46
Revises: 22f768cb411d
Create Date: 2025-09-29 07:16:28.118867

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'e49a289a6c46'
down_revision = '22f768cb411d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('scheduled_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'scheduled_date')
    # ### end Alembic commands ###
