/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodosRouteImport } from './routes/_layout/todos'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGmailRouteImport } from './routes/_layout/gmail'
import { Route as LayoutFinanceRouteImport } from './routes/_layout/finance'
import { Route as LayoutEmailTransactionsDashboardRouteImport } from './routes/_layout/email-transactions-dashboard'
import { Route as LayoutEmailTransactionsRouteImport } from './routes/_layout/email-transactions'
import { Route as LayoutEmailDashboardRouteImport } from './routes/_layout/email-dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutGmailIndexRouteImport } from './routes/_layout/gmail/index'
import { Route as LayoutGmailTransactionsRouteImport } from './routes/_layout/gmail/transactions'
import { Route as LayoutFinanceTransactionsRouteImport } from './routes/_layout/finance/transactions'
import { Route as LayoutFinanceIncomesRouteImport } from './routes/_layout/finance/incomes'
import { Route as LayoutFinanceCategoriesRouteImport } from './routes/_layout/finance/categories'
import { Route as LayoutFinanceAllocationRulesRouteImport } from './routes/_layout/finance/allocation-rules'
import { Route as LayoutFinanceAccountsRouteImport } from './routes/_layout/finance/accounts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosRoute = LayoutTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGmailRoute = LayoutGmailRouteImport.update({
  id: '/gmail',
  path: '/gmail',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceRoute = LayoutFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailTransactionsDashboardRoute =
  LayoutEmailTransactionsDashboardRouteImport.update({
    id: '/email-transactions-dashboard',
    path: '/email-transactions-dashboard',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutEmailTransactionsRoute = LayoutEmailTransactionsRouteImport.update({
  id: '/email-transactions',
  path: '/email-transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailDashboardRoute = LayoutEmailDashboardRouteImport.update({
  id: '/email-dashboard',
  path: '/email-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGmailIndexRoute = LayoutGmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutGmailRoute,
} as any)
const LayoutGmailTransactionsRoute = LayoutGmailTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutGmailRoute,
} as any)
const LayoutFinanceTransactionsRoute =
  LayoutFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => LayoutFinanceRoute,
  } as any)
const LayoutFinanceIncomesRoute = LayoutFinanceIncomesRouteImport.update({
  id: '/incomes',
  path: '/incomes',
  getParentRoute: () => LayoutFinanceRoute,
} as any)
const LayoutFinanceCategoriesRoute = LayoutFinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutFinanceRoute,
} as any)
const LayoutFinanceAllocationRulesRoute =
  LayoutFinanceAllocationRulesRouteImport.update({
    id: '/allocation-rules',
    path: '/allocation-rules',
    getParentRoute: () => LayoutFinanceRoute,
  } as any)
const LayoutFinanceAccountsRoute = LayoutFinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutFinanceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/email-dashboard': typeof LayoutEmailDashboardRoute
  '/email-transactions': typeof LayoutEmailTransactionsRoute
  '/email-transactions-dashboard': typeof LayoutEmailTransactionsDashboardRoute
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/gmail': typeof LayoutGmailRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/finance/incomes': typeof LayoutFinanceIncomesRoute
  '/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/gmail/transactions': typeof LayoutGmailTransactionsRoute
  '/gmail/': typeof LayoutGmailIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/email-dashboard': typeof LayoutEmailDashboardRoute
  '/email-transactions': typeof LayoutEmailTransactionsRoute
  '/email-transactions-dashboard': typeof LayoutEmailTransactionsDashboardRoute
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/finance/incomes': typeof LayoutFinanceIncomesRoute
  '/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/gmail/transactions': typeof LayoutGmailTransactionsRoute
  '/gmail': typeof LayoutGmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/email-dashboard': typeof LayoutEmailDashboardRoute
  '/_layout/email-transactions': typeof LayoutEmailTransactionsRoute
  '/_layout/email-transactions-dashboard': typeof LayoutEmailTransactionsDashboardRoute
  '/_layout/finance': typeof LayoutFinanceRouteWithChildren
  '/_layout/gmail': typeof LayoutGmailRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/todos': typeof LayoutTodosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/_layout/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/_layout/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/_layout/finance/incomes': typeof LayoutFinanceIncomesRoute
  '/_layout/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/_layout/gmail/transactions': typeof LayoutGmailTransactionsRoute
  '/_layout/gmail/': typeof LayoutGmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/email-dashboard'
    | '/email-transactions'
    | '/email-transactions-dashboard'
    | '/finance'
    | '/gmail'
    | '/items'
    | '/settings'
    | '/todos'
    | '/'
    | '/finance/accounts'
    | '/finance/allocation-rules'
    | '/finance/categories'
    | '/finance/incomes'
    | '/finance/transactions'
    | '/gmail/transactions'
    | '/gmail/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/email-dashboard'
    | '/email-transactions'
    | '/email-transactions-dashboard'
    | '/finance'
    | '/items'
    | '/settings'
    | '/todos'
    | '/'
    | '/finance/accounts'
    | '/finance/allocation-rules'
    | '/finance/categories'
    | '/finance/incomes'
    | '/finance/transactions'
    | '/gmail/transactions'
    | '/gmail'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/email-dashboard'
    | '/_layout/email-transactions'
    | '/_layout/email-transactions-dashboard'
    | '/_layout/finance'
    | '/_layout/gmail'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/todos'
    | '/_layout/'
    | '/_layout/finance/accounts'
    | '/_layout/finance/allocation-rules'
    | '/_layout/finance/categories'
    | '/_layout/finance/incomes'
    | '/_layout/finance/transactions'
    | '/_layout/gmail/transactions'
    | '/_layout/gmail/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos': {
      id: '/_layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof LayoutTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gmail': {
      id: '/_layout/gmail'
      path: '/gmail'
      fullPath: '/gmail'
      preLoaderRoute: typeof LayoutGmailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance': {
      id: '/_layout/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof LayoutFinanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-transactions-dashboard': {
      id: '/_layout/email-transactions-dashboard'
      path: '/email-transactions-dashboard'
      fullPath: '/email-transactions-dashboard'
      preLoaderRoute: typeof LayoutEmailTransactionsDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-transactions': {
      id: '/_layout/email-transactions'
      path: '/email-transactions'
      fullPath: '/email-transactions'
      preLoaderRoute: typeof LayoutEmailTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email-dashboard': {
      id: '/_layout/email-dashboard'
      path: '/email-dashboard'
      fullPath: '/email-dashboard'
      preLoaderRoute: typeof LayoutEmailDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/gmail/': {
      id: '/_layout/gmail/'
      path: '/'
      fullPath: '/gmail/'
      preLoaderRoute: typeof LayoutGmailIndexRouteImport
      parentRoute: typeof LayoutGmailRoute
    }
    '/_layout/gmail/transactions': {
      id: '/_layout/gmail/transactions'
      path: '/transactions'
      fullPath: '/gmail/transactions'
      preLoaderRoute: typeof LayoutGmailTransactionsRouteImport
      parentRoute: typeof LayoutGmailRoute
    }
    '/_layout/finance/transactions': {
      id: '/_layout/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof LayoutFinanceTransactionsRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/incomes': {
      id: '/_layout/finance/incomes'
      path: '/incomes'
      fullPath: '/finance/incomes'
      preLoaderRoute: typeof LayoutFinanceIncomesRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/categories': {
      id: '/_layout/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof LayoutFinanceCategoriesRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/allocation-rules': {
      id: '/_layout/finance/allocation-rules'
      path: '/allocation-rules'
      fullPath: '/finance/allocation-rules'
      preLoaderRoute: typeof LayoutFinanceAllocationRulesRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/accounts': {
      id: '/_layout/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof LayoutFinanceAccountsRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
  }
}

interface LayoutFinanceRouteChildren {
  LayoutFinanceAccountsRoute: typeof LayoutFinanceAccountsRoute
  LayoutFinanceAllocationRulesRoute: typeof LayoutFinanceAllocationRulesRoute
  LayoutFinanceCategoriesRoute: typeof LayoutFinanceCategoriesRoute
  LayoutFinanceIncomesRoute: typeof LayoutFinanceIncomesRoute
  LayoutFinanceTransactionsRoute: typeof LayoutFinanceTransactionsRoute
}

const LayoutFinanceRouteChildren: LayoutFinanceRouteChildren = {
  LayoutFinanceAccountsRoute: LayoutFinanceAccountsRoute,
  LayoutFinanceAllocationRulesRoute: LayoutFinanceAllocationRulesRoute,
  LayoutFinanceCategoriesRoute: LayoutFinanceCategoriesRoute,
  LayoutFinanceIncomesRoute: LayoutFinanceIncomesRoute,
  LayoutFinanceTransactionsRoute: LayoutFinanceTransactionsRoute,
}

const LayoutFinanceRouteWithChildren = LayoutFinanceRoute._addFileChildren(
  LayoutFinanceRouteChildren,
)

interface LayoutGmailRouteChildren {
  LayoutGmailTransactionsRoute: typeof LayoutGmailTransactionsRoute
  LayoutGmailIndexRoute: typeof LayoutGmailIndexRoute
}

const LayoutGmailRouteChildren: LayoutGmailRouteChildren = {
  LayoutGmailTransactionsRoute: LayoutGmailTransactionsRoute,
  LayoutGmailIndexRoute: LayoutGmailIndexRoute,
}

const LayoutGmailRouteWithChildren = LayoutGmailRoute._addFileChildren(
  LayoutGmailRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutEmailDashboardRoute: typeof LayoutEmailDashboardRoute
  LayoutEmailTransactionsRoute: typeof LayoutEmailTransactionsRoute
  LayoutEmailTransactionsDashboardRoute: typeof LayoutEmailTransactionsDashboardRoute
  LayoutFinanceRoute: typeof LayoutFinanceRouteWithChildren
  LayoutGmailRoute: typeof LayoutGmailRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTodosRoute: typeof LayoutTodosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutEmailDashboardRoute: LayoutEmailDashboardRoute,
  LayoutEmailTransactionsRoute: LayoutEmailTransactionsRoute,
  LayoutEmailTransactionsDashboardRoute: LayoutEmailTransactionsDashboardRoute,
  LayoutFinanceRoute: LayoutFinanceRouteWithChildren,
  LayoutGmailRoute: LayoutGmailRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTodosRoute: LayoutTodosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
