/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodosRouteImport } from './routes/_layout/todos'
import { Route as LayoutSprintFinanceRouteImport } from './routes/_layout/sprint-finance'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutMonthlyFinanceRouteImport } from './routes/_layout/monthly-finance'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSprintFinanceIndexRouteImport } from './routes/_layout/sprint-finance/index'
import { Route as LayoutSprintFinanceTransactionsRouteImport } from './routes/_layout/sprint-finance/transactions'
import { Route as LayoutSprintFinanceSprintsRouteImport } from './routes/_layout/sprint-finance/sprints'
import { Route as LayoutSprintFinanceSprintDetailRouteImport } from './routes/_layout/sprint-finance/sprint-detail'
import { Route as LayoutSprintFinanceIncomesRouteImport } from './routes/_layout/sprint-finance/incomes'
import { Route as LayoutSprintFinanceCategoriesRouteImport } from './routes/_layout/sprint-finance/categories'
import { Route as LayoutSprintFinanceAllocationRulesRouteImport } from './routes/_layout/sprint-finance/allocation-rules'
import { Route as LayoutSprintFinanceAccountsRouteImport } from './routes/_layout/sprint-finance/accounts'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosRoute = LayoutTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSprintFinanceRoute = LayoutSprintFinanceRouteImport.update({
  id: '/sprint-finance',
  path: '/sprint-finance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMonthlyFinanceRoute = LayoutMonthlyFinanceRouteImport.update({
  id: '/monthly-finance',
  path: '/monthly-finance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSprintFinanceIndexRoute =
  LayoutSprintFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceTransactionsRoute =
  LayoutSprintFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceSprintsRoute =
  LayoutSprintFinanceSprintsRouteImport.update({
    id: '/sprints',
    path: '/sprints',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceSprintDetailRoute =
  LayoutSprintFinanceSprintDetailRouteImport.update({
    id: '/sprint-detail',
    path: '/sprint-detail',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceIncomesRoute =
  LayoutSprintFinanceIncomesRouteImport.update({
    id: '/incomes',
    path: '/incomes',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceCategoriesRoute =
  LayoutSprintFinanceCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceAllocationRulesRoute =
  LayoutSprintFinanceAllocationRulesRouteImport.update({
    id: '/allocation-rules',
    path: '/allocation-rules',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)
const LayoutSprintFinanceAccountsRoute =
  LayoutSprintFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => LayoutSprintFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/monthly-finance': typeof LayoutMonthlyFinanceRoute
  '/settings': typeof LayoutSettingsRoute
  '/sprint-finance': typeof LayoutSprintFinanceRouteWithChildren
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/sprint-finance/accounts': typeof LayoutSprintFinanceAccountsRoute
  '/sprint-finance/allocation-rules': typeof LayoutSprintFinanceAllocationRulesRoute
  '/sprint-finance/categories': typeof LayoutSprintFinanceCategoriesRoute
  '/sprint-finance/incomes': typeof LayoutSprintFinanceIncomesRoute
  '/sprint-finance/sprint-detail': typeof LayoutSprintFinanceSprintDetailRoute
  '/sprint-finance/sprints': typeof LayoutSprintFinanceSprintsRoute
  '/sprint-finance/transactions': typeof LayoutSprintFinanceTransactionsRoute
  '/sprint-finance/': typeof LayoutSprintFinanceIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/items': typeof LayoutItemsRoute
  '/monthly-finance': typeof LayoutMonthlyFinanceRoute
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/sprint-finance/accounts': typeof LayoutSprintFinanceAccountsRoute
  '/sprint-finance/allocation-rules': typeof LayoutSprintFinanceAllocationRulesRoute
  '/sprint-finance/categories': typeof LayoutSprintFinanceCategoriesRoute
  '/sprint-finance/incomes': typeof LayoutSprintFinanceIncomesRoute
  '/sprint-finance/sprint-detail': typeof LayoutSprintFinanceSprintDetailRoute
  '/sprint-finance/sprints': typeof LayoutSprintFinanceSprintsRoute
  '/sprint-finance/transactions': typeof LayoutSprintFinanceTransactionsRoute
  '/sprint-finance': typeof LayoutSprintFinanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/monthly-finance': typeof LayoutMonthlyFinanceRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/sprint-finance': typeof LayoutSprintFinanceRouteWithChildren
  '/_layout/todos': typeof LayoutTodosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/sprint-finance/accounts': typeof LayoutSprintFinanceAccountsRoute
  '/_layout/sprint-finance/allocation-rules': typeof LayoutSprintFinanceAllocationRulesRoute
  '/_layout/sprint-finance/categories': typeof LayoutSprintFinanceCategoriesRoute
  '/_layout/sprint-finance/incomes': typeof LayoutSprintFinanceIncomesRoute
  '/_layout/sprint-finance/sprint-detail': typeof LayoutSprintFinanceSprintDetailRoute
  '/_layout/sprint-finance/sprints': typeof LayoutSprintFinanceSprintsRoute
  '/_layout/sprint-finance/transactions': typeof LayoutSprintFinanceTransactionsRoute
  '/_layout/sprint-finance/': typeof LayoutSprintFinanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/monthly-finance'
    | '/settings'
    | '/sprint-finance'
    | '/todos'
    | '/'
    | '/sprint-finance/accounts'
    | '/sprint-finance/allocation-rules'
    | '/sprint-finance/categories'
    | '/sprint-finance/incomes'
    | '/sprint-finance/sprint-detail'
    | '/sprint-finance/sprints'
    | '/sprint-finance/transactions'
    | '/sprint-finance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/items'
    | '/monthly-finance'
    | '/settings'
    | '/todos'
    | '/'
    | '/sprint-finance/accounts'
    | '/sprint-finance/allocation-rules'
    | '/sprint-finance/categories'
    | '/sprint-finance/incomes'
    | '/sprint-finance/sprint-detail'
    | '/sprint-finance/sprints'
    | '/sprint-finance/transactions'
    | '/sprint-finance'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/items'
    | '/_layout/monthly-finance'
    | '/_layout/settings'
    | '/_layout/sprint-finance'
    | '/_layout/todos'
    | '/_layout/'
    | '/_layout/sprint-finance/accounts'
    | '/_layout/sprint-finance/allocation-rules'
    | '/_layout/sprint-finance/categories'
    | '/_layout/sprint-finance/incomes'
    | '/_layout/sprint-finance/sprint-detail'
    | '/_layout/sprint-finance/sprints'
    | '/_layout/sprint-finance/transactions'
    | '/_layout/sprint-finance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos': {
      id: '/_layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof LayoutTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sprint-finance': {
      id: '/_layout/sprint-finance'
      path: '/sprint-finance'
      fullPath: '/sprint-finance'
      preLoaderRoute: typeof LayoutSprintFinanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/monthly-finance': {
      id: '/_layout/monthly-finance'
      path: '/monthly-finance'
      fullPath: '/monthly-finance'
      preLoaderRoute: typeof LayoutMonthlyFinanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sprint-finance/': {
      id: '/_layout/sprint-finance/'
      path: '/'
      fullPath: '/sprint-finance/'
      preLoaderRoute: typeof LayoutSprintFinanceIndexRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/transactions': {
      id: '/_layout/sprint-finance/transactions'
      path: '/transactions'
      fullPath: '/sprint-finance/transactions'
      preLoaderRoute: typeof LayoutSprintFinanceTransactionsRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/sprints': {
      id: '/_layout/sprint-finance/sprints'
      path: '/sprints'
      fullPath: '/sprint-finance/sprints'
      preLoaderRoute: typeof LayoutSprintFinanceSprintsRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/sprint-detail': {
      id: '/_layout/sprint-finance/sprint-detail'
      path: '/sprint-detail'
      fullPath: '/sprint-finance/sprint-detail'
      preLoaderRoute: typeof LayoutSprintFinanceSprintDetailRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/incomes': {
      id: '/_layout/sprint-finance/incomes'
      path: '/incomes'
      fullPath: '/sprint-finance/incomes'
      preLoaderRoute: typeof LayoutSprintFinanceIncomesRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/categories': {
      id: '/_layout/sprint-finance/categories'
      path: '/categories'
      fullPath: '/sprint-finance/categories'
      preLoaderRoute: typeof LayoutSprintFinanceCategoriesRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/allocation-rules': {
      id: '/_layout/sprint-finance/allocation-rules'
      path: '/allocation-rules'
      fullPath: '/sprint-finance/allocation-rules'
      preLoaderRoute: typeof LayoutSprintFinanceAllocationRulesRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
    '/_layout/sprint-finance/accounts': {
      id: '/_layout/sprint-finance/accounts'
      path: '/accounts'
      fullPath: '/sprint-finance/accounts'
      preLoaderRoute: typeof LayoutSprintFinanceAccountsRouteImport
      parentRoute: typeof LayoutSprintFinanceRoute
    }
  }
}

interface LayoutSprintFinanceRouteChildren {
  LayoutSprintFinanceAccountsRoute: typeof LayoutSprintFinanceAccountsRoute
  LayoutSprintFinanceAllocationRulesRoute: typeof LayoutSprintFinanceAllocationRulesRoute
  LayoutSprintFinanceCategoriesRoute: typeof LayoutSprintFinanceCategoriesRoute
  LayoutSprintFinanceIncomesRoute: typeof LayoutSprintFinanceIncomesRoute
  LayoutSprintFinanceSprintDetailRoute: typeof LayoutSprintFinanceSprintDetailRoute
  LayoutSprintFinanceSprintsRoute: typeof LayoutSprintFinanceSprintsRoute
  LayoutSprintFinanceTransactionsRoute: typeof LayoutSprintFinanceTransactionsRoute
  LayoutSprintFinanceIndexRoute: typeof LayoutSprintFinanceIndexRoute
}

const LayoutSprintFinanceRouteChildren: LayoutSprintFinanceRouteChildren = {
  LayoutSprintFinanceAccountsRoute: LayoutSprintFinanceAccountsRoute,
  LayoutSprintFinanceAllocationRulesRoute:
    LayoutSprintFinanceAllocationRulesRoute,
  LayoutSprintFinanceCategoriesRoute: LayoutSprintFinanceCategoriesRoute,
  LayoutSprintFinanceIncomesRoute: LayoutSprintFinanceIncomesRoute,
  LayoutSprintFinanceSprintDetailRoute: LayoutSprintFinanceSprintDetailRoute,
  LayoutSprintFinanceSprintsRoute: LayoutSprintFinanceSprintsRoute,
  LayoutSprintFinanceTransactionsRoute: LayoutSprintFinanceTransactionsRoute,
  LayoutSprintFinanceIndexRoute: LayoutSprintFinanceIndexRoute,
}

const LayoutSprintFinanceRouteWithChildren =
  LayoutSprintFinanceRoute._addFileChildren(LayoutSprintFinanceRouteChildren)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutMonthlyFinanceRoute: typeof LayoutMonthlyFinanceRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSprintFinanceRoute: typeof LayoutSprintFinanceRouteWithChildren
  LayoutTodosRoute: typeof LayoutTodosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutMonthlyFinanceRoute: LayoutMonthlyFinanceRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSprintFinanceRoute: LayoutSprintFinanceRouteWithChildren,
  LayoutTodosRoute: LayoutTodosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
