/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTodosRouteImport } from './routes/_layout/todos'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutRoadmapRouteImport } from './routes/_layout/roadmap'
import { Route as LayoutResourcesRouteImport } from './routes/_layout/resources'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFinanceRouteImport } from './routes/_layout/finance'
import { Route as LayoutEmailRouteImport } from './routes/_layout/email'
import { Route as LayoutDailyTodosRouteImport } from './routes/_layout/daily-todos'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutEmailIndexRouteImport } from './routes/_layout/email/index'
import { Route as LayoutFinanceTransactionsDashboardRouteImport } from './routes/_layout/finance/transactions-dashboard'
import { Route as LayoutFinanceTransactionsRouteImport } from './routes/_layout/finance/transactions'
import { Route as LayoutFinanceCategoriesRouteImport } from './routes/_layout/finance/categories'
import { Route as LayoutFinanceAllocationRulesRouteImport } from './routes/_layout/finance/allocation-rules'
import { Route as LayoutFinanceAccountsRouteImport } from './routes/_layout/finance/accounts'
import { Route as LayoutEmailTransactionsRouteImport } from './routes/_layout/email/transactions'
import { Route as LayoutEmailDashboardRouteImport } from './routes/_layout/email/dashboard'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTodosRoute = LayoutTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRoadmapRoute = LayoutRoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutResourcesRoute = LayoutResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFinanceRoute = LayoutFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailRoute = LayoutEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDailyTodosRoute = LayoutDailyTodosRouteImport.update({
  id: '/daily-todos',
  path: '/daily-todos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEmailIndexRoute = LayoutEmailIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutEmailRoute,
} as any)
const LayoutFinanceTransactionsDashboardRoute =
  LayoutFinanceTransactionsDashboardRouteImport.update({
    id: '/transactions-dashboard',
    path: '/transactions-dashboard',
    getParentRoute: () => LayoutFinanceRoute,
  } as any)
const LayoutFinanceTransactionsRoute =
  LayoutFinanceTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => LayoutFinanceRoute,
  } as any)
const LayoutFinanceCategoriesRoute = LayoutFinanceCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => LayoutFinanceRoute,
} as any)
const LayoutFinanceAllocationRulesRoute =
  LayoutFinanceAllocationRulesRouteImport.update({
    id: '/allocation-rules',
    path: '/allocation-rules',
    getParentRoute: () => LayoutFinanceRoute,
  } as any)
const LayoutFinanceAccountsRoute = LayoutFinanceAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => LayoutFinanceRoute,
} as any)
const LayoutEmailTransactionsRoute = LayoutEmailTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutEmailRoute,
} as any)
const LayoutEmailDashboardRoute = LayoutEmailDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutEmailRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/daily-todos': typeof LayoutDailyTodosRoute
  '/email': typeof LayoutEmailRouteWithChildren
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/resources': typeof LayoutResourcesRoute
  '/roadmap': typeof LayoutRoadmapRoute
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/email/dashboard': typeof LayoutEmailDashboardRoute
  '/email/transactions': typeof LayoutEmailTransactionsRoute
  '/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/finance/transactions-dashboard': typeof LayoutFinanceTransactionsDashboardRoute
  '/email/': typeof LayoutEmailIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/daily-todos': typeof LayoutDailyTodosRoute
  '/finance': typeof LayoutFinanceRouteWithChildren
  '/items': typeof LayoutItemsRoute
  '/resources': typeof LayoutResourcesRoute
  '/roadmap': typeof LayoutRoadmapRoute
  '/settings': typeof LayoutSettingsRoute
  '/todos': typeof LayoutTodosRoute
  '/': typeof LayoutIndexRoute
  '/email/dashboard': typeof LayoutEmailDashboardRoute
  '/email/transactions': typeof LayoutEmailTransactionsRoute
  '/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/finance/transactions-dashboard': typeof LayoutFinanceTransactionsDashboardRoute
  '/email': typeof LayoutEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/daily-todos': typeof LayoutDailyTodosRoute
  '/_layout/email': typeof LayoutEmailRouteWithChildren
  '/_layout/finance': typeof LayoutFinanceRouteWithChildren
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/resources': typeof LayoutResourcesRoute
  '/_layout/roadmap': typeof LayoutRoadmapRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/todos': typeof LayoutTodosRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/email/dashboard': typeof LayoutEmailDashboardRoute
  '/_layout/email/transactions': typeof LayoutEmailTransactionsRoute
  '/_layout/finance/accounts': typeof LayoutFinanceAccountsRoute
  '/_layout/finance/allocation-rules': typeof LayoutFinanceAllocationRulesRoute
  '/_layout/finance/categories': typeof LayoutFinanceCategoriesRoute
  '/_layout/finance/transactions': typeof LayoutFinanceTransactionsRoute
  '/_layout/finance/transactions-dashboard': typeof LayoutFinanceTransactionsDashboardRoute
  '/_layout/email/': typeof LayoutEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/daily-todos'
    | '/email'
    | '/finance'
    | '/items'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/todos'
    | '/'
    | '/email/dashboard'
    | '/email/transactions'
    | '/finance/accounts'
    | '/finance/allocation-rules'
    | '/finance/categories'
    | '/finance/transactions'
    | '/finance/transactions-dashboard'
    | '/email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/daily-todos'
    | '/finance'
    | '/items'
    | '/resources'
    | '/roadmap'
    | '/settings'
    | '/todos'
    | '/'
    | '/email/dashboard'
    | '/email/transactions'
    | '/finance/accounts'
    | '/finance/allocation-rules'
    | '/finance/categories'
    | '/finance/transactions'
    | '/finance/transactions-dashboard'
    | '/email'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/daily-todos'
    | '/_layout/email'
    | '/_layout/finance'
    | '/_layout/items'
    | '/_layout/resources'
    | '/_layout/roadmap'
    | '/_layout/settings'
    | '/_layout/todos'
    | '/_layout/'
    | '/_layout/email/dashboard'
    | '/_layout/email/transactions'
    | '/_layout/finance/accounts'
    | '/_layout/finance/allocation-rules'
    | '/_layout/finance/categories'
    | '/_layout/finance/transactions'
    | '/_layout/finance/transactions-dashboard'
    | '/_layout/email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/todos': {
      id: '/_layout/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof LayoutTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/roadmap': {
      id: '/_layout/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof LayoutRoadmapRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/resources': {
      id: '/_layout/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof LayoutResourcesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/finance': {
      id: '/_layout/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof LayoutFinanceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email': {
      id: '/_layout/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof LayoutEmailRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/daily-todos': {
      id: '/_layout/daily-todos'
      path: '/daily-todos'
      fullPath: '/daily-todos'
      preLoaderRoute: typeof LayoutDailyTodosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/email/': {
      id: '/_layout/email/'
      path: '/'
      fullPath: '/email/'
      preLoaderRoute: typeof LayoutEmailIndexRouteImport
      parentRoute: typeof LayoutEmailRoute
    }
    '/_layout/finance/transactions-dashboard': {
      id: '/_layout/finance/transactions-dashboard'
      path: '/transactions-dashboard'
      fullPath: '/finance/transactions-dashboard'
      preLoaderRoute: typeof LayoutFinanceTransactionsDashboardRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/transactions': {
      id: '/_layout/finance/transactions'
      path: '/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof LayoutFinanceTransactionsRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/categories': {
      id: '/_layout/finance/categories'
      path: '/categories'
      fullPath: '/finance/categories'
      preLoaderRoute: typeof LayoutFinanceCategoriesRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/allocation-rules': {
      id: '/_layout/finance/allocation-rules'
      path: '/allocation-rules'
      fullPath: '/finance/allocation-rules'
      preLoaderRoute: typeof LayoutFinanceAllocationRulesRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/finance/accounts': {
      id: '/_layout/finance/accounts'
      path: '/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof LayoutFinanceAccountsRouteImport
      parentRoute: typeof LayoutFinanceRoute
    }
    '/_layout/email/transactions': {
      id: '/_layout/email/transactions'
      path: '/transactions'
      fullPath: '/email/transactions'
      preLoaderRoute: typeof LayoutEmailTransactionsRouteImport
      parentRoute: typeof LayoutEmailRoute
    }
    '/_layout/email/dashboard': {
      id: '/_layout/email/dashboard'
      path: '/dashboard'
      fullPath: '/email/dashboard'
      preLoaderRoute: typeof LayoutEmailDashboardRouteImport
      parentRoute: typeof LayoutEmailRoute
    }
  }
}

interface LayoutEmailRouteChildren {
  LayoutEmailDashboardRoute: typeof LayoutEmailDashboardRoute
  LayoutEmailTransactionsRoute: typeof LayoutEmailTransactionsRoute
  LayoutEmailIndexRoute: typeof LayoutEmailIndexRoute
}

const LayoutEmailRouteChildren: LayoutEmailRouteChildren = {
  LayoutEmailDashboardRoute: LayoutEmailDashboardRoute,
  LayoutEmailTransactionsRoute: LayoutEmailTransactionsRoute,
  LayoutEmailIndexRoute: LayoutEmailIndexRoute,
}

const LayoutEmailRouteWithChildren = LayoutEmailRoute._addFileChildren(
  LayoutEmailRouteChildren,
)

interface LayoutFinanceRouteChildren {
  LayoutFinanceAccountsRoute: typeof LayoutFinanceAccountsRoute
  LayoutFinanceAllocationRulesRoute: typeof LayoutFinanceAllocationRulesRoute
  LayoutFinanceCategoriesRoute: typeof LayoutFinanceCategoriesRoute
  LayoutFinanceTransactionsRoute: typeof LayoutFinanceTransactionsRoute
  LayoutFinanceTransactionsDashboardRoute: typeof LayoutFinanceTransactionsDashboardRoute
}

const LayoutFinanceRouteChildren: LayoutFinanceRouteChildren = {
  LayoutFinanceAccountsRoute: LayoutFinanceAccountsRoute,
  LayoutFinanceAllocationRulesRoute: LayoutFinanceAllocationRulesRoute,
  LayoutFinanceCategoriesRoute: LayoutFinanceCategoriesRoute,
  LayoutFinanceTransactionsRoute: LayoutFinanceTransactionsRoute,
  LayoutFinanceTransactionsDashboardRoute:
    LayoutFinanceTransactionsDashboardRoute,
}

const LayoutFinanceRouteWithChildren = LayoutFinanceRoute._addFileChildren(
  LayoutFinanceRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDailyTodosRoute: typeof LayoutDailyTodosRoute
  LayoutEmailRoute: typeof LayoutEmailRouteWithChildren
  LayoutFinanceRoute: typeof LayoutFinanceRouteWithChildren
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutResourcesRoute: typeof LayoutResourcesRoute
  LayoutRoadmapRoute: typeof LayoutRoadmapRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutTodosRoute: typeof LayoutTodosRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDailyTodosRoute: LayoutDailyTodosRoute,
  LayoutEmailRoute: LayoutEmailRouteWithChildren,
  LayoutFinanceRoute: LayoutFinanceRouteWithChildren,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutResourcesRoute: LayoutResourcesRoute,
  LayoutRoadmapRoute: LayoutRoadmapRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutTodosRoute: LayoutTodosRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
